name : Deploiement formulaire
on : 
   push : 
    branches : 
      - master 
jobs : 
  deploy : 
    runs-on : ubuntu-latest
steps : 
  - name : Recup code 
    uses : actions/checkout@v4
  - name : Passe 2
    uses : peaceiris/actions-git-pages@v3
    with : 
      publish-dir : ./
      github_token : ${{secrets.GITHUB_TOKEN}}
permissions:
  contents : write
                                    
                                  
                      